### ISSUE TITLE
Usage of the lock-pattern activity

### ISSUE THREAD

**Issue by evxzibit** [haibison/android-lockpattern#29]
Good day,

This is not an issue but a question instead. I am new to android and would like to create almost the same app as on your demo(e.g a menu with create and enter pattern). My question is the following: Do i need to create another activity where i will put the menu buttons and then call the method startActivityForResult(intent, REQ_CREATE_PATTERN/REQ_ENTER_PATTERN ); when a button is clicked?  in other words, where does one put your "USAGE - Create new pattern" code ? in the main activity or in another created one...

Thank you in advance

**Comment by haibison** [comment]
Hello,

I'm very sorry. In order to understand the [Quick Use](Quick-Use), please learn how to make a basic Android app first. I don't have energy (and time) to help you with that.

For example if this library requires a level of 5, please achieve yourself a level of 4 (or at least 3). I can't help you from 0.
