### ISSUE TITLE
R.java not found when the project import to eclipse

### ISSUE THREAD

**Issue by afifzi** [haibison/android-lockpattern#31]
This project have some error because R.java not found

is there any that can fix the error?

thank you
![untitled](https://cloud.githubusercontent.com/assets/7928815/7611734/876abd42-f9b0-11e4-9668-4894374e099b.png)

**Comment by haibison** [comment]
Hello Afif,

Would you please list the steps you used to import the project into Eclipse? Did you clone the source here? Or did you take it from somewhere?

**Comment by afifzi** [comment]
I download project from https://github.com/haibison/android-lockpattern/tree/eclipse
I just import project to eclipse and R.java not found
can you explain detail of the Quick Use this project because i am not understand your  quick use

**Comment by haibison** [comment]
I'm very sorry. Please tell me your problem in details. Otherwise I can't help.

The source here contains some symbolic links (in Linux system). If you're using Windows or other OS which doesn't support symbolic links, please replace those links with real files. When compiling the project, Eclipse will mark those files as invalid files. You can open those files (they are plain text) and see the path to original files.

**Comment by haibison** [comment]
And also the source here is not stable. If you could, please use the source come with the [demo app](https://play.google.com/store/apps/details?id=group.pals.android.lib.ui.lockpattern.demo).
