### ISSUE TITLE
Get introduced pattern in ACTION_COMPARE_PATTERN

### ISSUE THREAD

**Issue by AlexGascon** [haibison/android-lockpattern#38]
Hello everyone. Hope you're having a nice day.

I'm implementing the lock pattern in my app. In order to prevent brute-force attacks, when the user creates a pattern and I hash the resulting char array using a slow-hashing function (concretely, BCrypt). 

The problem comes when the user tries to log again. The comparing action needs a pattern to compare with (EXTRA_PATTERN), but as I'm using a hashing function, I can't recover it. Would it be possible to, when calling to LockPatternActivity.ACTION_COMPARE_PATTERN, get the pattern that the user has introduced instead of just a result code?

Another possible option could be a disguised call to LockPatternActivity.ACTION_CREATE_PATTERN, that already returns the introduced pattern, but I would need it to ask the pattern only one time (without needing to re-enter it as confirmation).

Please, don't hesitate to ask me if I haven't explained well. Thank you so much in advance for your help and for your time.

**Comment by haibison** [comment]
Hi Alex,

Thanks  :-)  Have a nice day too.

The answer for both questions with `ACTION_COMPARE_PATTERN`, `ACTION_CREATE_PATTERN` is: Currently those options are not available.

For the case of `ACTION_COMPARE_PATTERN`, even if you get the pattern, you will have a newly raw-pattern along with an old encrypted-pattern, that won't help either.

---

I don't know much about encryption, so please correct me if I'm wrong:

I think to compare newly created pattern to the one saved before, we have to decrypt the old one. Because one original string can be encrypted to different strings with a same password -- so comparing them won't work. If you agree, please consider reading this page: [Encryption](../wiki/Encryption). I hope it will help.

**Comment by haibison** [comment]
Hi Alex,

I'm closing the issue. However, feel free to add your comments. I'll open it again if necessary...
