### ISSUE TITLE
i want todesign  

### ISSUE THREAD

**Issue by dongjingun** [haibison/android-lockpattern#45]

**Comment by dongjingun** [comment]
other  pattern ,no   only  the cycle

**Comment by haibison** [comment]
@dongjingun 

Hi  :-)

I think you want to draw another shape instead of a circle for each dot. If you do, please have a look at this file [`LockPatternView.java`]. It contains all code which displays/draws the pattern.

[`LockPatternView.java`]: https://github.com/haibison/android-lockpattern/blob/master/app/src/main/java/haibison/android/lockpattern/widget/LockPatternView.java

**Comment by dongjingun** [comment]
thanks a lot ,i had solve it

**Comment by haibison** [comment]
You're welcome.

Have a nice day  :-)
